### ISSUE TITLE
"Show live" issue

### ISSUE THREAD

**Issue by Capuce08** [emlyon/Designing-With-Web#13]
I have a problem with the option "Show live" in Glitch. 
When I click on it, I am redirected to a new page titled "listing directory" with many elements : .data, .views, .git etc, and my file "index.htlm". But then when I click on it, this file is saved on my computer and impossible to open on Google Chrome. 
And if I open it with Internet Explorer or Firefox, the new page shows only the codes that I have typed, and not the result (for example it shows <em>TEXT</em> and not TEXT emphasized). 
Could you help me with this issue ?
Best regards

**Comment by MAKIO135** [comment]
It seems that your HTML file is not named ìndex.html`

**Comment by Capuce08** [comment]
Yes it is named like that and it doesn't work...

**Comment by MAKIO135** [comment]
HTML, not HTLM

**Comment by MAKIO135** [comment]
Can you send me a link to your project?

**Comment by Capuce08** [comment]
It's okay, it's works !
Thank you very much

Le 10 oct. 2018 5:17 PM, Lionel RADISSON <notifications@github.com> a écrit :

Can you send me a link to your project?
