### ISSUE TITLE
Delete a submission of the glitch project in module 5

### ISSUE THREAD

**Issue by tristanlegallriou** [emlyon/Designing-With-Web#15]
Hello!
I do not know if it is possible to delete projects i have been submitting in module 5 because I realized they did not match properly with the requirements... Is there any way to fix that issue?
Thank you for your time,

Tristan LE GALL--RIOU

**Comment by MAKIO135** [comment]
Hello Tristan,

You can either modify the code in your project before the deadline of part 1, or simply post a new url.
