### ISSUE TITLE
How to use $.getJSON() ?

### ISSUE THREAD

**Issue by sarah-cnv** [emlyon/Designing-With-Web#16]
Hi everyone,

I'm currently working on our second assignment, and I can't figure how to use $.getJSON() to load something on my page...
Here my project so far : [https://designing-with-web-project-2.glitch.me/](url)
Can someone explain how to implement that in my work ?

Thanks

**Comment by MAKIO135** [comment]
Hello Sarah, 
See "Loading data & dynamic content" section in **7. JS libraries** that is dedicated to that.
You can also consult these links for more informations:
- https://api.jquery.com/jQuery.getJSON/
- https://www.sitepoint.com/ajaxjquery-getjson-simple-example/
- https://javabeat.net/jquery-getjson-example/
