### ISSUE TITLE
A dream of the future

### ISSUE THREAD

**Issue by JulianeLACROIX** [emlyon/Designing-With-Web#18]
Bonjour Monsieur, 

Je ne comprends pas pourquoi quand j'appuie sur show live, j'ai cette image qui apparaît ...
<img width="378" alt="capture" src="https://user-images.githubusercontent.com/43675671/47013976-319d2480-d149-11e8-9194-88a71663dc0f.PNG">
" a dream of the future, 
Oh hi,

Tell me your hopes and dreams..."

Je pense que c'est un problème lié au nom du document, mais je ne sais pas lequel 

Merci d'avance

**Comment by MAKIO135** [comment]
Bonjour Julianne, Lorsque tu crées un nouveau projet sur Glitch, Glitch te propose 3 templates différents. Je te conseille de démarrer avec Hello-Webpage
![capture d ecran 2018-10-16 a 14 30 23](https://user-images.githubusercontent.com/1162231/47016485-1681e300-d150-11e8-8502-9d696d897457.png)
Tu auras juste un fichier `index.html`, un fichier CSS et un fichier JS
