### ISSUE TITLE
error message on brightspace

### ISSUE THREAD

**Issue by maymgr** [emlyon/Designing-With-Web#2]
Hello,
Even though I am following the course on an updated version of chrome, I sometime have error messages like the one you'll find attached. It's still there even I refresh the page.
![message d erreur](https://user-images.githubusercontent.com/43471478/45882254-e001b400-bdad-11e8-971f-a418e21e7411.jpeg)

**Comment by laetitiaemlyon** [comment]
I have the same issue on all  Glich embed with Google chrome 69.

[emlyon.brightspace.com-1537783388540.log](https://github.com/emlyon/Designing-With-Web/files/2410385/emlyon.brightspace.com-1537783388540.log)

![capture](https://user-images.githubusercontent.com/43536064/45946614-b33dde80-bff1-11e8-914e-9b7c51303519.PNG)

**Comment by MAKIO135** [comment]
@maymgr @laetitiaemlyon Thanks for reporting this issue.
Please come to the makers'lab staff office (in front of the makers'lab) during opening hours so that we find a solution to your problem.

**Comment by MAKIO135** [comment]
@laetitiaemlyon from your log, it seems you're loading the whole part 1. As explained at the end of the introduction to part 1, you should use the menu on the left in Brightspace to load modules individually.

**Comment by MAKIO135** [comment]
@maymgr on Chrome, you can do `[ Cmd ] + [ Maj ] + [ r ]` on mac / `[ Ctrl ] + [ Maj ] + [ r ]` on Windows to completely reload page without using cache.

**Comment by MAKIO135** [comment]
@maymgr @laetitiaemlyon are you still having issues?

**Comment by maymgr** [comment]
No but I still switched to Firefox since it was easier . Thank you !

Obtenez Outlook pour iOS<https://aka.ms/o0ukef>

________________________________
De : Lionel RADISSON <notifications@github.com>
Envoyé : lundi, octobre 8, 2018 3:59 PM
À : emlyon/Designing-With-Web
Cc : MAGRÉ Maylis; Mention
Objet : Re: [emlyon/Designing-With-Web] error message on brightspace (#2)


@maymgr<https://github.com/maymgr> @laetitiaemlyon<https://github.com/laetitiaemlyon> are you still having issues?
