### ISSUE TITLE
Coding part changed color

### ISSUE THREAD

**Issue by solenenaeye** [emlyon/Designing-With-Web#22]
Main issue: 

Tout était bien en bleu pour <p> automatiquement et d'un coup une grosse partie de mon code est devenue rouge et noir ? Qu'est-ce que cela signifie? Comment faire?

Autres questions: 

Pourquoi il y a-t-il une erreur dans cette ligne?
<img src="https://cdn.glitch.com/3720c480-ac5d-40e8-b79d-6830fa0b30a2%2Fcaldecott_055.png?1539767489288" height="40%" width=40%">

dans celle-ci:
<div style="width:100%;height:0;padding-bottom:44%;position:relative;"><iframe src="https://giphy.com/embed/l1ugrgqm3PwBs3Rja" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/am85-cine-mexicano-peliculas-mexicanas-l1ugrgqm3PwBs3Rja">via GIPHY</a></p>

Pourtant tout s'affiche correctement sur mon site.

**Comment by MAKIO135** [comment]
> Tout était bien en bleu pour
> automatiquement et d'un coup une grosse partie de mon code est devenue rouge et noir ? Qu'est-ce que cela signifie? Comment faire?  
Que veux tu dire? ajoute une capture d'écran

Et poste le lien vers l'éditeur de ton projet, car l'erreur vient probablement d'une ligne précédente

**Comment by solenenaeye** [comment]
J'ai réussi à résoudre une partie, cependant, je ne comprends pas pourquoi mes colonnes ne s'affichent plus normalement (à part pour la première fable) alors qu'avant tout était OK.

Merci de votre aide

Solène

lien: https://glitch.com/edit/#!/fables-solenenaeye?path=index.html:74:6

**Comment by MAKIO135** [comment]
ajoute `</div>` sur la ligne 100

**Comment by MAKIO135** [comment]
il te manque un `</p>`à rajouter juste avant le `</div>`que tu viens de mettre

**Comment by solenenaeye** [comment]
Dernière pastille rouge à la dernière ligne: 

</html> alors qu'il est ouvert qu'une fois dans la ligne 3?

Je ne comprends pas pourquoi?

Merci

Solène

**Comment by solenenaeye** [comment]
+ 1 titre (le troisième) ne s'affiche plus normalement, je ne comprends pas ce qui change alors que je ne touche plus à ces lignes de code?

**Comment by solenenaeye** [comment]
Ok pour le titre, j'ai trouvé, il manquait un </div>

Par contre pour le </html> je ne comprends toujours pas. :)

**Comment by MAKIO135** [comment]
les éléments `link`devraient être dans le `head`et tu ouvres 2 fois le `body`.

**Comment by solenenaeye** [comment]
Je ne comprends pas
