### ISSUE TITLE
Misunderstanding about "console.log"

### ISSUE THREAD

**Issue by mathismaury** [emlyon/Designing-With-Web#23]
I am currently doing the Assignment 2 but I have a problem with the "console.log", I don't understand how to see what this function is supposed to show while working on Glitch. So it is hard to do the assignment as I can't see the structure of the json files I want to use...

If someone could help me it would be great ! 😃

**Comment by MAKIO135** [comment]
right click on your page and click "inspect" to open developers tools, then click on the "console" tab to see the result of your `console.log()`

**Comment by mathismaury** [comment]
Ok thank you very much it works !
