### ISSUE TITLE
Reload new API inputs

### ISSUE THREAD

**Issue by Vincentrichardemlyon** [emlyon/Designing-With-Web#25]
Bonjour,
Je charge l'API random user sur mon [site](https://second-as.glitch.me/),
Ensuite avec le bouton "looks so friendly !"  j'ajoute le nom du random user dans la liste,
J'aimerai ensuite que ce même bouton rafraîchisse l'API et me charge un nouveau random user. 

J'ai trouvé la fonction pour "fade out" l'ancien contenu en revanche je n'arrive pas à rafraîchir l'API et charger un nouveau user. Soit j'obtient un rafraîchissement de l'URL (ce que je ne veux pas) soit une erreur tout simplement.

Pourriez vous m'aider sur cette impasse ? 
Voici le lien de mon glitch : https://glitch.com/edit/#!/second-as
Merci

**Comment by MAKIO135** [comment]
Bonjour j'essaie de t'aider sur Glitch en ce moment

**Comment by MAKIO135** [comment]
https://rune-puma.glitch.me/

**Comment by Vincentrichardemlyon** [comment]
Merci, c'est exactement ce que je voulais faire.
En revanche je ne comprend pas comment se fait t'il qu'on arrive à appeler 
 ` var username = user.name.first + " " + user.name.last`
dans la fonction
```
 $("#like").on( "click", function() {
  var username = user.name.first + " " + user.name.last
  var li = ( "<li><img src='"+user.picture.large+"'>"+ username + "</li>" );
  likedlist.append( li );

  profile.fadeOut();
  getNewUser();// call it again on click
} ); 
```
alors que les données viennes d'une autre fonction ? (en revanche ici la fonction _function getNewUser()_)

Merci

**Comment by MAKIO135** [comment]
Ligne 5 `var user;`, je déclare ce qu'on appelle une variable **globale**: une variable qui est déclarée à l'extérieur des fonctions du script. 
Je peux donc y accéder à n'importe quel endroit de mon script que ce soit à l'intérieur ou à l'extérieur de fonctions et ainsi lui assigner une valeur à l'intérieur de la fonction `getNewUser` et récupérer cette valeur dans une autre fonction.
Alors que les arguments d'une fonction ou les variables créées dans une fonction ne sont accessibles que dans cette fonction (on dit qu'elles ont une portée locale), les variables créées à l'extérieur de fonctions sont accessibles de partout (on parle de portée globale). 

Tu peux regarder le lien suivant pour en apprendre plus sur le "scope des variables": https://www.w3schools.com/js/js_scope.asp
