### ISSUE TITLE
What does the requirements of assignment mean?

### ISSUE THREAD

**Issue by XIAODAN95** [emlyon/Designing-With-Web#26]
Dear Professor,

I'm confused with one of requirement of AI Assignment -- be correctly documented(it can be replicated from your doc).

Could you explain or rephrase it?

Thank you.

Regards,
Xiaodan ZHOU

**Comment by MAKIO135** [comment]
Hello,
 i rephrased it on Brightspace to "it could be implemented from your documentation" 
**If someone should code your application, she/he should find (nearly) all the resources needed to do so in your documentation.**
