### ISSUE TITLE
Documentation Webhooks

### ISSUE THREAD

**Issue by solenenaeye** [emlyon/Designing-With-Web#28]
Bonjour, 

J'ai choisi le module APIs, j'ai compris le principe. J'ai ensuite créé mon applet grâce à IFTTT et aux services suivants:
- Date and time
- SMS
Cette applet fonctionne. 

Je ne comprends cependant pas la partie Documentation avec la key que l'on doit récupérer.
A quoi correspond:
-event?
-value1 / value 2 / value 3

Merci pour votre aide.

Cordialement

Solène NAEYE

**Comment by MAKIO135** [comment]
Bonjour,

**Les webhooks sont un moyen de déclencher une action sur IFTTT par la programmation en envoyant une requête HTTP** (comme nous l'avons fait avec getJSON() à la fin de la partie 1). 

Imaginons une page Web avec un formulaire, à chaque fois qu'un utilisateur soumet le formulaire (clique sur un bouton), nous pouvons en JS récupérer les données du formulaire et faire une requête HTTP à IFTTT afin de déclencher un Webhooks. Le paramètre `event` de notre requête sert simplement de nom pour savoir quel applet IFTTT actionner, c'est pourquoi lorsque vous créez un applet avec un webhook vous devez donnez le nom de l'`event`qui déclenchera cet applet. Par ailleurs, avec notre requête JS, nous pouvons passer également des données, comme les champs du formulaire rempli par notre utilisateur. Pour passer ces données nous pouvons utiliser les paramètres `value1, value2,value3`(eg `value1 = nom de l'utilisateur dans le formulaire`. Ces paramètres peuvent être récupérés dans l'action à déclencher pour la personnaliser, par exemple, vous envoyer un SMS avec le nom l'utilisateur. Enfin la clé, correspond au "mot de passe" pour déclencher **vos webhooks**, les noms d'`event` pouvant être les mêmes pour plusieurs personnes, avec la clé vous assurez l'identification de vos Webhooks.

(Nous pourrions le faire aussi à chaque qu'un utilisateur clique sur un élément/ charge la page /... et prendre des données comme l'heure, l'élément cliqué, l'url de la page, l'IP de l'utilisateur, sa géolocalisation, son type de navigateur,...)

Enfin, je ne vous demande pas de coder cette application, mais de la documenter, la décrire, dans quel contexte, pourquoi, pour qui, où quand, comment, quelles technologies utiliser pour l'implémenter, avez vous des références à citer, ...

**Comment by solenenaeye** [comment]
Merci pour votre réponse complète.

Il y a-t-il donc suffisamment d'informations dans ce site?

https://textpil.glitch.me/

Merci

Solène
