### ISSUE TITLE
[IFTTT API assignment] clarifications

### ISSUE THREAD

**Issue by Vincentrichardemlyon** [emlyon/Designing-With-Web#29]
Hello, 
I am currently working on the API assignment, 
It is asking to use _IFTTT webhooks to create an applet._ 
This mean that we must use the webhook trigger to do an action ? 
And cannot use another trigger "IF" like weather underground or time clock to make our _useful_ applet ? 

Thanks,
Vincent

**Comment by MAKIO135** [comment]
Hello Vincent,

You're right, however in your concept application you could have a device with temperature/humidity/barometric pressure/... captors (see https://learn.adafruit.com/wifi-weather-station-with-tft-display/overview) that make the HTTP request to use Webhooks and trigger your applet. You don't need to make it, you need to document it.

**Comment by Vincentrichardemlyon** [comment]
Ok thank you for the information,
Best regards,
Vincent
