### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by claraananou** [emlyon/Designing-With-Web#30]
Hello sir, 

Just like the others I struggle to understand what we have to do on the second assignment even with the precisions you added on the homepage.  Should we just modify the JSON data of the example you gave us ? If so, do we have to change the CSS and the HTML ? 
I tried remixing your example by changing the JSON data and getting JSON data from colourlovers but I don't understand what I have to do after line 16 in the code (line 16 includes your comments). Is there a special property for colourlovers JSON ? If so, how do we find it ? 
Sorry for not understanding but the course is great though ! 

Clara Ananou

**Comment by MAKIO135** [comment]
Hello Clara,

You may have understood that with the `getJSON`method we can load data. This is just like a big JS Object with many properties / sub properties / arrays / etc... From this data and jQuery's methods to create HTML elements, you can add to your page titles / paragraphs / images based on the values inside this data, like using the value of the name property of a user inside a paragraph element . This is exactly the goal of this assignment: load data and create content dynamically from this data.

**Comment by claraananou** [comment]
Hello sir, 

So I think I have understood how to dig an information into JSON data. But now, I don't really understand how it is supposed to appear in HTML. I have tried reading the jQuery.each() link you put to explain the $.each in your example but it is not clear to me. Could you clarify it please? 
Thank you 
Clara Ananou

**Comment by MAKIO135** [comment]
the `$.each` method is used for working with arrays (See "*JS - Arrays*" if needed). This method takes 2 parameters: 
- an array
- a function with 2 parameters (explanation below) to apply for each elements of the array. 
The `$.each` method will call this second parameter function for every items in the array passed as first parameter: the function will be called 5 times if there are 5 items in the array. For each element in the array the function is called with its first parameter set to the index of the element and its second parameter set to the value of the element.

Example:
```
var myArray = [ 3, 4, 6, 1 ];

$.each( myArray, function( index, element ) {
    console.log( index, element );  
} );
// will print in the console:
// "0, 3" for the first element
// "1, 4" for the second element
// "2, 6" for the third
// "3, 1" for the fourth
```
With our JSON data, we can use `$.each` to loop through our arrays of JS Objects: `element` will represent the first Object, then the second, then the third, ...

**Comment by claraananou** [comment]
But how is this displaying what we see on the console on to the webpage ? Should we use the $().appendTo() ?

**Comment by claraananou** [comment]
I succeeded in importing a picture from a link (here is my work: https://javascript-clara-devoir.glitch.me/) using $().appendTo() I found on api.jquery.com, is it ok ?

**Comment by MAKIO135** [comment]
> But how is this displaying what we see on the console on to the webpage ? Should we use the $().appendTo() ?

To display it in your webpage instead of the console you should use `$().append()` or any other method that can create an HTML element (like `$.appendTo()`):
```
var myArray = [ 3, 4, 6, 1 ];
$.each( myArray, function( index, element ) {
    $( 'body' ).append( "<p>Element at index " + index + " is " + element +"</p>" );  
} );
```
-> **Yes, your assignment seems to be ok.**
