### ISSUE TITLE
Positioning Javascript Content

### ISSUE THREAD

**Issue by Vincentrichardemlyon** [emlyon/Designing-With-Web#32]
Hello sir, 
I struggle since this morning with a simple thing.
I am currently working on the Machine Learning assignment, 
I followed the class of Coding Train and have my effective ML tool. 
Now, I want to integrate the script at a certain point of my website but anywhere I put the script it will load everything at the bottom of the page and not where I want it to be positioned. 

As i am using a template for my website it is very convenient for me to position the script according to where I write in my html and without using CSS. 
How can I say that i want the buttons and Canvas created by the JS script at a certain position in my page ? For instance I would like to be able to add a simple "div" (or whatever it should be?) with my JS function that create buttons and canva at the right position in my html.

You can see the problem [there ](https://my-little-ai.glitch.me/)(don't bother on the content) where my ML script is loaded at the bottom of the page. 

Thank you

**Comment by MAKIO135** [comment]
Hello Vincent,
It seems you are using p5js to create your elements like your `button`, so i created an example for you with p5js on  how to create your element inside a specific element, like a `div`
https://editor.p5js.org/makio135/sketches/H1KG2uHAm
