### ISSUE TITLE
API

### ISSUE THREAD

**Issue by claraananou** [emlyon/Designing-With-Web#33]
Bonjour,

Je ne suis pas sûre d'avoir compris les instructions du devoir sur les APIs. Est-ce que ceci suffit ou faut-il rajouter quelque chose avec l'Applet Webhooks que nous avons crée avec le cours ? 
https://api-claraananou.glitch.me/

Merci,
Clara Ananou

**Comment by MAKIO135** [comment]
Bonjour,

Vous devez rajouter des références vers des projets similaires, concurrents ou dans lesquels il manquerait justement ces fonctionnalités.
