### ISSUE TITLE
Customizing the webpage's content based on some JSON data 

### ISSUE THREAD

**Issue by rebeccataieb** [emlyon/Designing-With-Web#34]
Hi,

I am trying to use my JSON data to push a customized content but I don't know where to start. Basically I decided to use 10 different persons on the random user generator. At the beginning the program picks one of the 10 users based on a random choice, which allows me to greet one of them by its name. But then I would like to make a program that uses the person's gender (which I can find in the JSON data) to display either one or another picture. Is that possible ? 

Best Regards.

**Comment by MAKIO135** [comment]
Hello Rebecca,

Yes, that's possible. Basically, let's say you have in your JS script, `var gender = users[0].gender;` to get the gender of your first user.
From that you'll have to use a condition:
```
if( gender === "female" ) {
    // display image for "female"
}
else if( gender === "male" ) {
    // display image for "male"
}
else {
    // display image for "unknown/other"
}
```
You could either:
- have 2 `img`elements in your HTML document, with `style="display:none;"` to hide them at first (ie `<img id="female-image" style="display:none;" src="https://url.of/your/image.jpg">, then in your condition use `$("#female-image").show();` to display the image with `id=female-image`, or another one
- have an `img` element with an empty `src`: `<img id="gender-image" src="">`, and set its `src` value in your condition: `$("#gender-image").attr("src", "https://url.of/your/image.jpg");`

**Comment by rebeccataieb** [comment]
Ok I see. Can I also do the same with the text under the image by using $(#text).innertext("blabla for female") inside the list of instructions of the condition ? And does the corresponding element with id="text" in the html need to be empty or can there be something else written? Based on my comprehension of the course I would say it's either way, since previous text would be instantly overruled when the json is loaded, is that correct?

**Comment by MAKIO135** [comment]
Yes, it should be `$("#text").text("blah blah");` and the corresponding element can be empty. That is a totally correct understanding, but if set to anything the text will be visible during the short time the JSON is loaded.
