### ISSUE TITLE
I don't understand why my code does not work.

### ISSUE THREAD

**Issue by rebeccataieb** [emlyon/Designing-With-Web#35]
Good evening,

In the code joined I tried to modify the text of several elements with class "name" in my doc, replacing it by the first name property of my randomusergenerator json data. First I generate a random number to select the user in a list of 10. However it does not run & on the console it says that "user" is undefined, but it seems to me like it is defined. Could you help? Thanks a lot.

Best Regards. 

<img width="657" alt="code json" src="https://user-images.githubusercontent.com/44648809/49458942-2c299580-f7ee-11e8-8bd8-0c195b37e870.png">

**Comment by MAKIO135** [comment]
Send me an invitation link via email (click on the "share" button to get the link)

**Comment by rebeccataieb** [comment]
And I fear I'm gonna have the same problem for the rest of my code. Basically I would like that when the page is loaded one random number is generated once in for all, corresponding to one specific user, so that I can use 3 properties like gender, first name and location to change elements within the DOM. 


I send you the link right away via email.

**Comment by MAKIO135** [comment]
users are in `json.results` ;)

**Comment by rebeccataieb** [comment]
Hello again,

I have another issue with the following code. I tested it and it seems to work but not all the time. I have no idea if it is due to my wifi quality or if it is a flaw in the code (maybe in the way "j" is defined?). Do you have a clue about this? 

Best regards. 
<img width="759" alt="code 2" src="https://user-images.githubusercontent.com/44648809/49465971-2b4d2f80-f7ff-11e8-92dc-608cdf441186.png">

**Comment by MAKIO135** [comment]
Hello,
I don't get what you want to do with these lines:
```
var j=Math.round(Math.random()*10);
  if (j>3) {
    j=j-4;
  };
  console.log(j);
```

**Comment by rebeccataieb** [comment]
I only want to generate a random number between 0 and 3 in order to use it for my fake "loterie".

**Comment by MAKIO135** [comment]
```
var j = Math.floor( Math.random() * 4 );
```
Use `Math.floor()` instead of `Math.round()`, it will truncate the random value and only keep the integer part. And since `Math.random()` will draw a number between 0 and 0.999999999 ( it never reaches 1), `Math.random() * 4` will draw a number between 0 and 3.999999999. Thus `Math.floor( Math.random() * 4 )` will give you either 0, 1, 2 or 3.

**Comment by rebeccataieb** [comment]
Ok, thank you very much. I guess it must be the reason of the bug, since the rest of the code seems fine to me.

**Comment by MAKIO135** [comment]
The problem was that 
```
var j=Math.round(Math.random()*10); // get an integer between 0 and 10 included
  if (j>3) {
    j=j-4;
  };
  console.log(j); // j could have a value between 0 and 6 included ( more than your array )
```

**Comment by rebeccataieb** [comment]
Indeed, I see it now, I didn't notice that when I devised it. Thanks again.

**Comment by MAKIO135** [comment]
i made another change to draw a new number on each `click`events

**Comment by rebeccataieb** [comment]
To be honest, I don't quite see where you made the change  regarding the event listening part.

**Comment by MAKIO135** [comment]
I moved the `var j=Math.round(Math.random()*10);` line inside the callback of the `click` event

**Comment by rebeccataieb** [comment]
Oh, right! However, now that I think about it it might not be the right way to go, because it means that by clicking a lot of times you are sure to get the prize you prefer, which would make gaming companies completely broke. Although since it's a fake one it does not really matter, and now I know the difference.

**Comment by MAKIO135** [comment]
Indeed, you would need to identify the user to make sure they can't play twice

**Comment by MAKIO135** [comment]
exactly, it was a bit weird to see this incomplete part
