### ISSUE TITLE
Clarifications on API assignment

### ISSUE THREAD

**Issue by rebeccataieb** [emlyon/Designing-With-Web#36]
Hello,

I have a question on what you expect for the API project. Basically I have an idea of App that would prove very useful : I would like to suggest an App connected to my Bank mobile app so that whenever my account gets close to overdraft (let's say I have less than 20euros left) I receive an SMS notifying me and indicating the amount I have left. However, regarding the documentation, I am not sure how to do this, because my bank's app would need to have an existing API, which I am not sure it does. Besides I am not exactly sure what you ask: is it just an idea or something doable based on the few services currently represented on IFTTT? 

Best Regards.

**Comment by rebeccataieb** [comment]
But it does need to be an applet that does not exist yet on IFTTT right ?

**Comment by MAKIO135** [comment]
The applet in itself is not important. The concept is way more, and actually you've understand the needs of your application. The assignment is to imagine an application using IFTTT, describe the context/target/app and usage as well as what is needed in a technical point of view. So you could use your scenario and describe an IFTTT bank channel and document what it would need to work on IFTTT

**Comment by rebeccataieb** [comment]
Could you tell me if the documentation I just made makes sense to you (expecially the "technical part")? I am not very sure I am being clear enough since I don't know exactly the level of detail your require. 
Here is the link : https://alluring-parsnip.glitch.me/ ==> let me know if it is not what you expect. 

NB : just know that I did not do the css yet.

**Comment by MAKIO135** [comment]
Yes, that works!

Le mer. 5 déc. 2018 à 23:57, Rebecca TAIEB <notifications@github.com> a
écrit :
