### ISSUE TITLE
Page HTML et CSS pas reliées

### ISSUE THREAD

**Issue by ClemenceThomin** [emlyon/Designing-With-Web#38]
#### My problem relates to:
- Part: Ma page web ne se modifie pas lorsque je modifie ma page css
- Module: (module title)

#### I already tried to: 
-  J'ai déjà essayé de réouvrir le document et de recommencer l'écriture du programme.  
-
-

Link to my glitch project (editor view http://glitch.com/edit/...): https://glitch.com/edit/#!/hail-ox?path=index.html:7:28

**Comment by MAKIO135** [comment]
Effectivement. Regardez dans le cours comment lier un fichier CSS à une page Web (section How To Use CSS? dans CSS - Styling the Web)
