### ISSUE TITLE
SweetAlert

### ISSUE THREAD

**Issue by ValentinDUREL** [emlyon/Designing-With-Web#39]
#### My problem relates to:
- Part: 1
- Module: 7 Library

#### My problem is: 
I have some questions about the assignment and especially about sweet alert, I would like :

1- that we can't close the popup by not clicking on it

2- the window closes when I clic on "cancel".

3-to know if there is another way to use swal (I did not understand the functionning of the SWALTransformer). For me, I use a script like that `<script src="https://unpkg.com/sweetalert2@7.17.0/dist/sweetalert2.all.js"></script>`) 

#### I already tried to: 
1 - essayé avec la commande : `closeOnClickOutside : false` ça ne fait rien.
2-  I know how to do a button that closes the windows in the HTML but not in the swal  : 
```
<form>
    <input type="button" value="Fermer" onclick="self.close();">
</form>
``` 
3- already using a script

Link to my glitch project: https://glitch.com/edit/#!/valentindurel?path=main.js:1:0

**Comment by MAKIO135** [comment]
Updated to new version of swal.js. Fixed.
