### ISSUE TITLE
Skeleton grid

### ISSUE THREAD

**Issue by LauraMillot** [emlyon/Designing-With-Web#5]
Hello
I have issues with skeleton's grid. So from what I understood the grid allows to adapt the content of our page to smaller screens. But then can it be used as a table to design the layout of our page ? I don't get how the .row and .columns work 
Thanks

**Comment by MAKIO135** [comment]
When creating a div with the `row` class, you're creating a **container for columns**. This container takes the maximum width it can, whether it is inside a `.container`or not.

Inside this `.row`, you can create `div` elements with a `columns` class. Inside these `.columns`elements you can put title, text, images, videos, ...

A`.row` can be divided into **12 equal parts**, the width of each `.columns` is defined by a second class that is the number of parts it should take out of the 12. 

For example, if you want two equal columns:
```html
<div class="row">
    <div class="six columns"> <-- this is our first column -->
        <!-- here goes what should go inside the first column, you can put text elements, images, titles -->
    </div>

    <div class="six columns"> <-- this is our second column -->
        <!-- here goes what should go inside the second column, you can put text elements, images, titles -->
    </div>
</div>
```
Here we have 2 columns that take `six`parts each: `6 + 6 = 12`
If you want the first column bigger that the second: you could define your first colum with `class="height columns"` and the second with `class="four columns"`, `8 + 4 = 12`. 
But you could also create 3 `.columns`with that take `four` parts each, `3 * 4 = 12`, etc..

**Your columns should never take more than 12 parts.**

Is it more clear for you?

**Comment by MAKIO135** [comment]
Here, I coded a minimal playground to test skeleton's `.row` and `.columns`:
https://jsbin.com/jovanekoxu/edit?html,output
You can change the columns width, add new ones, remove the `.container`

**Comment by MAKIO135** [comment]
And by the way you should set your name in Github as asked in **module 0: basic setup**

**Comment by LauraMillot** [comment]
Thank you very much !

My name on brightspace is Laura Millot and it's the same on Github

**Comment by MAKIO135** [comment]
You're welcome.

> My name on brightspace is Laura Millot and it's the same on Github

Have you set it in your profile settings? It does not appear
![capture d ecran 2018-10-02 a 15 27 10](https://user-images.githubusercontent.com/1162231/46351555-f0d8e200-c657-11e8-878c-50a382d91324.png)

**Comment by LauraMillot** [comment]
Ok sorry i didn't understand, i just changed it, does it appear now ?

**Comment by NatachaGRANGER** [comment]
Good afternoon! I have issues with the display property : we have to do that => h1 and p elements have their display property set to block by default, but span elements are inline by default. Uncomment line 2, then set display property to inline and see how boxes are affected. Nevertheless, I don't understand what I have to do.. Thanks for your help!

**Comment by MAKIO135** [comment]
Hello,
"Uncomment line 2, then set `display` property to `inline` and see how boxes are affected."  
This consign is right below a glitch embed, displaying `style.css` file. **Line 2** of this file is: `/* display: block; */` remove the comment marks and write `inline`instead of `block`

And your issue isn't related to this one **Skeleton's grid are not responsive**, create new one next time.

**Comment by AlixLECOINTRE** [comment]
Hello, 
When I try to copy your codes (for js) to my glitch, the gifs don't display. 
How do you make it works?

**Comment by MAKIO135** [comment]
Unrelated, create a specific issue. 
Be more precise, send links / captures.
