### ISSUE TITLE
Problem: the text does not appear on the right

### ISSUE THREAD

**Issue by Lulululululululululu** [emlyon/Designing-With-Web#7]
I have a problem: when I click on wrap text, it does not appear on the right. What am I suppose to do ?
Thank you

**Comment by MAKIO135** [comment]
What do you mean by "wrap text"? could you add a screen capture? or a gif (try https://giphy.com/apps/giphycapture )

**Comment by MAKIO135** [comment]
Do you mean the "wrap text" option mentioned at the end of "starting with Glitch"? This does not make anything appear on the right. This option is used to avoid scrolling horizontally if your lines of code are longer than your screen.

**Comment by Lulululululululululu** [comment]
Ok I thought this enable us to see the result of what we write on the right of the screen.
My problem is that nothing appears on the right of my screen so if I want to see the result of what I write I have to click on "show live" and that is not very practical.
However on the gif explanations I saw that we are supposed to see the result of what we write on the right of our screen.
Thank you for you help
________________________________

**Comment by MAKIO135** [comment]
Sorry this confused you, but preview on the right works only with glitch projects embedded.
An alternative is to create 2 windows with your browser, one for the editor and one for the live view, and split them across your screen.

**Comment by Lulululululululululu** [comment]
Ok, thank you !
________________________________
